DROP TABLE IF EXISTS [Courses];
CREATE TABLE IF NOT EXISTS [Courses]
(
	[Id] CHAR(36) NOT NULL PRIMARY KEY,
	[Name] TEXT NOT NULL,
	[Status] INTEGER UNSIGNED NOT NULL DEFAULT 7
) WITHOUT ROWID;


DROP TABLE IF EXISTS [Topics];
CREATE TABLE IF NOT EXISTS [Topics]
(
	[Id] CHAR(36) NOT NULL PRIMARY KEY,
	[CourseId] CHAR(36) NOT NULL REFERENCES [Courses]([Id]),
	[Month] INTEGER UNSIGNED NOT NULL,
	[Hours] INTEGER UNSIGNED NOT NULL DEFAULT 4,
	[Description] TEXT NOT NULL,
	[Status] INTEGER UNSIGNED NOT NULL DEFAULT 7
	-- FOREIGN KEY [CourseId]) REFERENCES [Courses]([Id])
) WITHOUT ROWID;